apps/Problems/urls.py
from django.urls import path
from . import views

app_name = 'problems'

urlpatterns = [
    path('problem/create/', views.CreateProblem.as_view(), name='problemCreate'),
    path('problem/<int:pk>/', views.DetailProblem.as_view(), name='problemDetail'),
    path('problem/list/', views.ProblemListView.as_view(), name='problemList'),
    path('getPDF/', views.createPDF, name="createPDF"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from .settings import settings
from .settings.local_settings import ADMIN_PATH 

from django.conf import settings

from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path(ADMIN_PATH + '/', admin.site.urls),
]
urlpatterns += i18n_patterns(
    path('', include('apps.Problems.urls', namespace='problems')),
    path('', include('social_django.urls', namespace='social')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

apps/Problems/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

from datetime import datetime

from taggit.managers import TaggableManager



class Problem(models.Model):
    title = models.CharField(max_length=100, blank=False)

    statement = models.TextField(blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('problems:problemDetail',args=[self.id])

    def get_latex(self):
        return "\subsection{" + self.title+ "} \n" + self.statement

apps/Problems/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from .models import Problem



class DetailProblem(DetailView):
    model = Problem
    template_name = "problems/detail.html"

class CreateProblem(CreateView):
    model = Problem
    fields = ['title', 'statement'] 
    template_name = "problems/create.html"

class ProblemListView(ListView):
    context_object_name = "problems"
    model = Problem
    paginate_by = 100  
    template_name = "problems/list.html"


from django_tex.shortcuts import render_to_pdf

def createPDF(request):
    template_name = 'template.tex'
    problems = Problem.objects.all()
    code = ""
    for i in problems:
        code += i.get_latex()

    context = {'foo': 'Bar', 'problems':code}
    return render_to_pdf(request, template_name, context, filename='test.pdf')

fakestalmat/templates/base.html
{% load static %}
{% load sri %}
{% load i18n %}

<!DOCTYPE html>
<html lang="{{LANGUAGE_CODE}}">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="">

    <!-- TODO Add Favicon-->
    <link rel="shortcut icon" type="image/png" href="" alt="Page favicon."/>

    <!--Meta-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js" integrity="sha384-LQc6P0tjydf0IS2VO/iGZcRhIK1mYatxhr+EGHA361ABtAiPhLj0Y9H6zAqto47a" crossorigin="anonymous"></script>
    
    <script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3.0.0/es5/tex-mml-chtml.js"></script>
    <script>  window.MathJax = {tex: {inlineMath: [['$', '$'], ['$$', '$$']]}}; </script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
    <!-- Web CSS-->
    {% sri_static "css/base.css" %}
    {% block css%}
    {% endblock%}


    {% sri_static "js/base.js" %}

    {% csrf_token%}

    </head>

<body>
    <!-- Navbar  -->
    {% include 'navbar.html'%}

    <div id="main-content" class="main">
        {% block content %}
        {% endblock %}
    </div>
    
    {% block widgets %}
    {% endblock %}

    <!-- Footer section -->
    <!-- TODO Add footer-->
    <footer class="footer py-4 bg-dark text-white">
        <div class="container text-center">
            <small>Sin animo de lucro y con animo de ganar las olimpiadas</small>
        </div>
    </footer>


    <!-- Web JS-->
    {% block js%}
    {% endblock%}
</body>
</html>

fakestalmat/templates/home.html
{% extends 'base.htlm'%}
        
{% block content%}
<a href = "{% url 'problems:problemCreate'%}"><h1>Crear problema</h1></a>
<a href = "{% url 'problems:createPDF'%}"><h1>Crear createPDF</h1></a>
{% endblock %}
 

fakestalmat/templates/navbar.html
<div class="p-3 header">
<a href="{% url 'problems:problemList'%}" class="text-decoration-none"><h1 class="text-white"><strong>FakEstalMat</strong></h1></a>
</div>

fakestalmat/templates/problems/create.html
{% extends 'base.html'%}

{% block content%}
    <form action="?" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>          
{% endblock %}  

fakestalmat/templates/problems/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{object.title}}</h1>
    <p>{{object.statement}}</p>
{% endblock %}

fakestalmat/templates/problems/list.html
{% extends 'base.html'%}


{% block content %}
<div class="container py-4">
    <ul id="problem-list" class="list-group">
        {% for problem in problems %}
            <li class="list-group-item list-group-item-action">
                <a href="{{problem.get_absolute_url}}" class="text-decoration-none">
                    <h5 class="text-dark"><strong>{{problem.title}}</strong>
                        
                    </h5>
                </a>
            </li>
        {% endfor %}
    </div>
</div>
    

{% endblock %}